server.port = 8082
spring.application.name=manager-teams
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=32167321

#spring.security.user.name = dimon
#spring.security.user.password = 32167321


spring.jpa.hibernate.ddl-auto=update
